server:
  port: 8080
spring:
  application:
    name: spring-ai-alibaba-graph-demo
  ai:
    dashscope:
      api-key:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:graphedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: